
model_name=Nonstationary_Transformer

  python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path alabama_4h.csv  \
  --model_id alabama_Nonstationary_Transformer_epoch10 \
  --model $model_name \
  --data only_do  \
  --features M \
  --target 2423160 \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 24 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --d_model 128

  python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path alabama_4h.csv  \
  --model_id alabama_Nonstationary_Transformer_epoch10 \
  --model $model_name \
  --data only_do  \
  --features M \
  --target 2423160 \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 48 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --d_model 128

  python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path alabama_4h.csv  \
  --model_id alabama_Nonstationary_Transformer_epoch10 \
  --model $model_name \
  --data only_do  \
  --features M \
  --target 2423160 \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 72 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --d_model 128

  python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path alabama_4h.csv  \
  --model_id alabama_Nonstationary_Transformer_epoch10 \
  --model $model_name \
  --data only_do  \
  --features M \
  --target 2423160 \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --d_model 128

  python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path alabama_4h.csv  \
  --model_id alabama_Nonstationary_Transformer_epoch10 \
  --model $model_name \
  --data only_do  \
  --features M \
  --target 2423160 \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 120 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --d_model 128

  python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path alabama_4h.csv  \
  --model_id alabama_Nonstationary_Transformer_epoch10 \
  --model $model_name \
  --data only_do  \
  --features M \
  --target 2423160 \
  --seq_len 48 \
  --label_len 24 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 5 \
  --dec_in 5 \
  --c_out 5 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --d_model 128